version: '3.4'

services:
  vscode:
    image: $CI_REGISTRY_URL/code-server:v0.1.0-rc7
    restart: always
    # network_mode: host
    hostname: ${HOSTNAME:-MacBook-Pro}
    privileged: true
    build:
      context: .
    env_file: 
    - .env
    ports: 
      - 8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .tmp/vscode-cache:/root/.local/share/code-server
    # memswap_limit: -1
    command: code-server --port 8080 --user-data-dir /root/.local/share/code-server --extensions-dir /root/.vscode/extensions --allow-http --no-auth /root/Projects
